INSERT INTO JEUNES VALUES('Fleury','Rose',17,'rosyyy@mail.com','dgdtgh',1030)
INSERT INTO JEUNES VALUES('Natura', 'Filip',12,'fifo@mail.com','',1210)
INSERT INTO JEUNES VALUES('Mitura', 'Ofely',8,'Ofifi@mail.com','',1030)
INSERT INTO JEUNES VALUES('Mito', 'Tommy',7,'mytho@mail.com','',1030)
INSERT INTO JEUNES VALUES('Pavoshko', 'Rodrigue',16,'Roro@mail.com','',1000)




INSERT INTO RESPONSABLE VALUES('zizaoui','mohamed amine',23,'amine0520@hotmail.com','hkfjhjsklghtjksgh',1210,'étudiant')
INSERT INTO RESPONSABLE VALUES('ZIZOU','MINO',23, 'TAESHADOWMASTER@MAIL.COM','DFGTDYHYUK',1210,'ANIMATEUR')
INSERT INTO RESPONSABLE VALUES('KAZE','KAMI',25,'GROSDURE@MAIL.COM','FHJEGHJFHRJK',1030,'COACH SPORTIF')

INSERT INTO ACTIVITES VALUES('Basket-ball','',100,2022)
INSERT INTO ACTIVITES VALUES('Taekwondo','',200,2021)
INSERT INTO ACTIVITES VALUES('soutien scolaire','',40,2020)
INSERT INTO ACTIVITES VALUES('mini-foot','',60,2021)
INSERT INTO ACTIVITES VALUES('Taekwondo','',200,2020)

INSERT INTO INSCRIPTION(ID_JEUNES,ID_ACTIVITES) VALUES(13000,1)
INSERT INTO INSCRIPTION(ID_JEUNES,ID_ACTIVITES) VALUES(13000,2)
INSERT INTO INSCRIPTION(ID_JEUNES,ID_ACTIVITES) VALUES(13000,3)
INSERT INTO INSCRIPTION(ID_JEUNES,ID_ACTIVITES) VALUES(13001,4)
INSERT INTO INSCRIPTION(ID_JEUNES,ID_ACTIVITES) VALUES(13002,5)
INSERT INTO INSCRIPTION(ID_JEUNES,ID_ACTIVITES) VALUES(13003,1)
INSERT INTO INSCRIPTION(ID_JEUNES,ID_ACTIVITES) VALUES(13004,2)
INSERT INTO INSCRIPTION(ID_JEUNES,ID_ACTIVITES) VALUES(13003,3)