--VUE CONTENANT LA LISTE DES JEUNES QUI HABITENT SCHAERBEEK
CREATE VIEW JEUNES_SCHAERBEEKOIS AS SELECT * FROM JEUNES j WHERE CODE_POSTAL=1030 WITH CHECK OPTION
GO
select * from JEUNES_SCHAERBEEKOIS
GO



--VUE CONTENANT LA LISTES DES ACTIVITES ET DE LEUR RESPONSABLE
CREATE VIEW LISTE_ACTIVITES AS SELECT a.TITRE, r.NOM, r.PRENOM FROM ACTIVITES a join RESPONSABLE r   on a.ID_RESPONSABLE=r.CODE_RESPONSABLE
GO
SELECT * FROM LISTE_ACTIVITES
GO